INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE) values (10001, 'Pablo', 'Learn Spring Boot', CURRENT_DATE(), false)
INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE) values (10002, 'Pablo', 'Learn Spring Framework', CURRENT_DATE(), false)
INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE) values (10003, 'Pablo', 'Learn Angular', CURRENT_DATE(), false)
INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE) values (10004, 'Pablo', 'Learn MongoDB', CURRENT_DATE(), false)